# Generated by Django 3.2.9 on 2021-12-30 03:45

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=2000)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(blank=True, choices=[('O', 'ordered'), ('R', 'recorded'), ('S', 'sent'), ('D', 'delivered')], max_length=1, null=True)),
                ('branche_status', models.CharField(blank=True, choices=[('O', 'ordered'), ('R', 'recorded'), ('S', 'sent'), ('D', 'delivered')], max_length=1, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_main', models.BooleanField(null=True)),
                ('description', models.TextField(max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('category', models.ManyToManyField(null=True, related_name='food', to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('B', 'breakfast'), ('L', 'lunch'), ('D', 'dinner')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=store.models.get_uploade_path)),
                ('quantity', models.PositiveIntegerField()),
                ('branche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='store.branche')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='store.food')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='store.bill')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_meal',
            field=models.ManyToManyField(null=True, related_name='food', to='store.MealCategory'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200)),
                ('address', models.ManyToManyField(null=True, related_name='customer', to='store.Address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_user', to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='branche',
            name='category',
            field=models.ManyToManyField(null=True, related_name='branche', to='store.Category'),
        ),
        migrations.AddField(
            model_name='branche',
            name='resturant_mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.resturant'),
        ),
        migrations.AddField(
            model_name='branche',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='bill',
            name='choosen_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.branche'),
        ),
        migrations.AddField(
            model_name='bill',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='store.customer'),
        ),
    ]
