# Generated by Django 3.2.9 on 2022-01-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220103_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.address'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('O', 'ordered'), ('R', 'recorded'), ('S', 'sent'), ('D', 'delivered')], default='O', max_length=1, null=True),
        ),
    ]
