# Generated by Django 3.2.9 on 2022-01-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220105_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='store.customer'),
        ),
    ]
