# Generated by Django 3.2.9 on 2022-01-13 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branche',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branche', to=settings.AUTH_USER_MODEL),
        ),
    ]
