# Generated by Django 3.2.9 on 2021-12-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
