# Generated by Django 3.2.9 on 2022-01-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_costumuser_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
