# Generated by Django 3.2.9 on 2022-01-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_costumuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
